Repository aeternity/aepp-components, pull requests merged in 2018-08, with the labels that each got.

#127 Improve AeButton
  src/components/aeButton/aeButton.md
  src/components/aeButton/aeButton.vue
  src/components/aeModalLight/aeModalLight.md
  src/components/aeModalLight/aeModalLight.vue
Labels: v2

#125 Changes for Epoch version of the Base app
  package.json
  src/components/aeAddressInput/aeAddressInput.md
  src/components/aeAddressInput/aeAddressInput.test.js
  src/components/aeAddressInput/aeAddressInput.vue
  src/components/aeIdentity/aeIdentity.js
  src/components/aeIdentity/aeIdentity.md
  src/components/aeIdentity/aeIdentity.test.js
  src/components/aeIdentity/aeIdentity.vue
  src/components/aeIdentityLight/aeIdentityLight.js
  src/components/aeIdentityLight/aeIdentityLight.md
  src/components/aeIdentityLight/aeIdentityLight.test.js
  src/components/aeIdentityLight/aeIdentityLight.vue
Labels: v2

#130 adding @download/blockies as an external package
  config/webpack.config.js
Labels: v3

#136 removing redundant comments
  src/components/ae-address/ae-address.js
  src/components/ae-address/ae-address.test.js
  src/components/ae-address/index.js
  src/components/ae-avatar/ae-avatar.js
  src/components/ae-avatar/ae-avatar.test.js
  src/components/ae-avatar/index.js
  src/components/ae-backdrop/ae-backdrop.js
  src/components/ae-backdrop/ae-backdrop.test.js
  src/components/ae-backdrop/index.js
  src/components/ae-badge/ae-badge.js
  src/components/ae-badge/ae-badge.test.js
  src/components/ae-badge/index.js
  src/components/ae-button/ae-button.js
  src/components/ae-button/ae-button.test.js
  src/components/ae-button/index.js
  src/components/ae-card/ae-card.js
  src/components/ae-card/ae-card.test.js
  src/components/ae-card/index.js
  src/components/ae-check/ae-check.js
  src/components/ae-check/ae-check.test.js
  src/components/ae-check/index.js
  src/components/ae-drop/ae-drop.js
  src/components/ae-drop/ae-drop.test.js
  src/components/ae-drop/index.js
  src/components/ae-flip/ae-flip.js
  src/components/ae-flip/ae-flip.test.js
  src/components/ae-flip/index.js
  src/components/ae-icon/ae-icon.js
  src/components/ae-icon/ae-icon.test.js
  src/components/ae-icon/index.js
  src/components/ae-input/ae-input.js
  src/components/ae-input/ae-input.test.js
  src/components/ae-input/index.js
  src/components/ae-list-item/ae-list-item.js
  src/components/ae-list-item/ae-list-item.test.js
  src/components/ae-list-item/index.js
  src/components/ae-list/ae-list.js
  src/components/ae-list/ae-list.test.js
  src/components/ae-list/index.js
  src/components/ae-phraser/ae-phraser.js
  src/components/ae-phraser/ae-phraser.test.js
  src/components/ae-phraser/index.js
  src/components/ae-qrcode/ae-qrcode.js
  src/components/ae-qrcode/ae-qrcode.test.js
  src/components/ae-qrcode/index.js
  src/components/ae-text/ae-text.js
  src/components/ae-text/ae-text.test.js
  src/components/ae-text/index.js
  src/components/ae-toolbar/ae-toolbar.js
  src/components/ae-toolbar/ae-toolbar.test.js
  src/components/ae-toolbar/index.js
  src/components/ae-view/ae-view.js
  src/components/ae-view/ae-view.test.js
  src/components/ae-view/index.js
Labels: enhancement, v3

#135 replacing user-select mixin with css property, adding improvements to…
  src/base/globals/_mixins.scss
  src/components/ae-badge/ae-badge.scss
  src/components/ae-button/ae-button.scss
  src/components/ae-card/ae-card.scss
  src/components/ae-check/ae-check.scss
  src/components/ae-drop/ae-drop.scss
  src/components/ae-input/ae-input.scss
  src/components/ae-list-item/ae-list-item.js
  src/components/ae-list-item/ae-list-item.md
  src/components/ae-list-item/ae-list-item.scss
  src/components/ae-list-item/ae-list-item.vue
  src/components/ae-list/ae-list.js
  src/components/ae-list/ae-list.md
  src/components/ae-list/ae-list.scss
  src/components/ae-list/ae-list.vue
Labels: enhancement, v3
